[package]
name = "cacherch"
version = "0.1.0"
edition = "2024"

[dependencies]
console = "0.16.1"
tantivy = "0.25.0"
serde_json = "1.0.104"
serde = { version = "1.0.228", features = ["derive"] }
clap = { version = "4.5.50", features = ["derive"] }
tokio = {version = "1.48.0", features = ["full"] }
